inputType = input('Type something: ')
print('Type is:', type(inputType))
print('Just spaces? ', inputType.isspace())
print('It is a number? ', inputType.isnumeric())
print('It is alphabetic? ', inputType.isalpha())
print('It is alphanumeric? ', inputType.isalnum())
print('It is Uppercase letters? ', inputType.isupper())
print('It is Lowercase letters? ', inputType.islower())
print('It is capitalized? ', inputType.istitle())